#!/usr/bin/env bash
/opt/homebrew/bin/notmuch tag +protonmail -- is:new path:account.protonmail/**
/opt/homebrew/bin/notmuch tag +kelleys -- is:new path:account.kelleys/**
/opt/homebrew/bin/notmuch tag +heartex -- is:new path:account.heartex/**
$HOME/.pyenv/shims/afew --tag --new
$HOME/.pyenv/shims/afew --move-mails
