#!/usr/bin/env bash
/opt/homebrew/bin/notmuch tag +protonmail -- is:new path:account.protonmail/**
/opt/homebrew/bin/notmuch tag +kelleys -- is:new path:account.kelleys/**
/opt/homebrew/bin/notmuch tag +human-signal -- is:new path:account.human-signal/**
/opt/homebrew/bin/notmuch tag +calendar -new -- is:new attachment:*.ics
$HOME/.pyenv/shims/afew --tag --new
$HOME/.pyenv/shims/afew --move-mails
