#+title: dots

Configuring the universe, one spilled coffee at a time.

* What?
There's a few things configured here, and they change relatively often, but the major components are:
** emacs
#+html: <a href="https://orgmode.org"><img src="https://img.shields.io/badge/Org-literate%20config-%2377aa99?style=flat-square&logo=org&logoColor=white"></a>
Doom emacs with a focus on org mode and python/scala development.

I have a modular/literate config, so docs are included in the code and each major component of my config can be viewed separately.

I also have chemacs set up, which I only really use to declare emacs bankruptcy and start a new config.

** wezterm/nushell
For a terminal emulator, I use wezterm (a quick and modern terminal emulator with a human readable/editable config file and modular keybindings).

For a shell, I use nushell (a quick shell with nice semantics).

** chezmoi
bootstrapping tool for linking configurations to the appropriate place

** yabai/skhd
tiling window manager for macos, and its keybinding software

* Installation
On a new machine:

#+BEGIN_SRC sh
xcode-select --install  # if not installed already
sh -c "$(curl -fsLS get.chezmoi.io)" -- init --apply pakelley/...
#+END_SRC

To re-run:

#+BEGIN_SRC sh
chezmoi apply
#+END_SRC

Notably, the scripts are only set up for configuring a mac for now.

For reference, this is what I still need after running the script:
- Activate licenses for the few apps I'm willing to pay for (fantastical, dash, raycast)
- Log into whatever needs it (spotify, anki (web), etc)
- Log into Zotero, add [[https://retorque.re/zotero-better-bibtex/installation/][BetterBibTeX]] extension, and [[https://blog.tecosaur.com/tmio/2021-07-31-citations.html#working-with-zotero][set up auto-export]]
- Install "Fenced code plus" Logseq plugin for mermaid support, and setup zotero integration
