#+title: dots

Configuring the universe, one spilled coffee at a time.
* What?
There's a few things configured here, and they change relatively often, but the mojor components are:
** emacs
The pièce de résistance. I use doom emacs with a focus on org mode, and python/scala development. I have a modular literate config set up, so each major component of my config can be viewed separately.
I also have chemacs set up, which I only really use when I have to declare emacs bankruptcy and start up a new config.
** wezterm/nushell
My terminal set up uses wezterm (a quick/modern terminal emulator with a real config file and modular keybindings) and nushell (quick shell with nice semantics).
** mackup
bootstrapping tool for linking configurations to the appropriate place
** yabai/skhd
tiling window manager for macos, and its keybinding software
* Installation
If you want to assimilate, clone the repo and run `bin/virus.exe` in your shell from the root directory of the repo.
The script is made to be idempotent, so you should be able to safely re-run at any point.
Also, notably, the script is only set up for configuring a mac for now.
For reference, this is what I still need after running the script:
- Allow a few apps access to various things (yabai, skhd, karabiner, etc)
- Set up my syncthing folders (as of now, my notes, alfred preferences, and calibre library)
- Activate licenses for the few apps I'm willing to pay for (alfred, fantastical, dash)
- Add Keepass database
- Log into whatever needs it (spotify, anki (web), etc)
- Add anki connect plugin
  - tools -> addons -> get addons -> 2055492159 (code for anki connect addon) -> restart anki
