#+property: header-args:emacs-lisp :tangle yes
#+property: header-args:elisp :tangle yes

* Packages
#+begin_src elisp :tangle packages.el
(package! benchmark-init)
#+end_src
* Set theme
For now, I like this one. We'll see how long it lasts.
#+begin_src elisp
(setq doom-theme 'doom-oceanic-next)
#+end_src
* Set localleader key
I don't like pressing two keys for my localleader... And you have to unbind evil-snipe's "," conflict.
#+begin_src elisp
(setq evil-snipe-override-evil-repeat-keys nil)
(setq doom-localleader-key ",")
(setq doom-localleader-alt-key "M-,")
#+end_src
* Set "SPC SPC" to call M-x, because I use M-x so often (and I miss this setting from spacemacs).
#+begin_src elisp
(map! (:leader
       :desc "M-x"  "SPC" #'execute-extended-command))
#+end_src
* Set window bindings
I think these are easier to remember than the doom defaults (plus they're what I use in tmux)
#+begin_src elisp
(map! (:map evil-window-map
       "/" #'+evil-window-vsplit-a
       "?" #'+evil/window-vsplit-and-follow
       "-" #'+evil-window-split-a
       "_" #'+evil/window-split-and-follow))
#+end_src
* Relative line numbers
Makes it easier to prefix commands with numbers (e.g. `5 j` would go 5 down, and I can see where that will put me with relative line numbers)
#+begin_src elisp
(setq display-line-numbers-type 'relative)
#+end_src
* Shorten path in modeline
Makes working in a monorepo less terrible
#+begin_src emacs-lisp
(after! doom-modeline
  (setq doom-modeline-major-mode-icon t)
  (setq doom-modeline-buffer-encoding nil)
  (setq doom-modeline-buffer-file-name-style 'truncate-with-project))
#+end_src
* Make evil-paste not kill (because it's usually more annoying than helpful for me)
#+begin_src elisp
(setq-default evil-kill-on-visual-paste nil)
#+end_src
* Keybinding to add buffer to a workspace (via persp)
#+begin_src emacs-lisp :tangle yes
(use-package! persp-mode
  :commands persp-add-buffer
  :config
  (map! :leader
        (:prefix ("TAB" . "workspace")
         :desc "Add buffer to a workspace" "a" #'persp-add-buffer)))
#+end_src
