# tap "spotify/public"
brew "azure-cli"
brew "azcopy"
brew "awscli"
brew "cmake"
brew "datasette"
# brew "docker", link: false
brew "docuum", restart_service: true
brew "dvc"
# brew "gibo"
brew "helm"
brew "ankitpokhrel/jira-cli/jira-cli"
brew "kubernetes-cli"
brew "k9s"
brew "minikube"
brew "ncspot"
brew "cava"  # visualizer I use w/ ncspot

brew "ollama"
# brew "packer"
brew "pipx"
brew "podman"
brew "pre-commit"
brew "rage"  # for age encryption
brew "age-plugin-yubikey"
brew "sqlite-utils" # mostly to convert to sqlite for datasette
# brew "terraform"
# brew "spotify/public/gcs-parquet-cli"
brew "zellij"
cask "docker"
cask "google-cloud-sdk"
# cask "lens"
# cask "ngrok"
# cask "nteract"
cask "orbstack"
# cask "postman"
cask "podman-desktop"
