# tap "spotify/public"
brew "azure-cli"
brew "azcopy"
brew "awscli"
brew "cmake"
# brew "docker", link: false
brew "docuum", restart_service: true
# brew "gibo"
brew "helm"
brew "ankitpokhrel/jira-cli/jira-cli"
brew "kubernetes-cli"
brew "k9s"
brew "minikube"
brew "ollama"
# brew "packer"
brew "pipx"
brew "pre-commit"
# brew "terraform"
# brew "spotify/public/gcs-parquet-cli"
cask "docker"
cask "google-cloud-sdk"
# cask "lens"
# cask "ngrok"
# cask "nteract"
# cask "postman"
