brew gerbv
cask "gimp"
cask "gnucash"
cask "hammerspoon"
cask "inkscape"
# cask "iterm2"
cask "kicad"
cask "libreoffice"
cask "malwarebytes"
cask "qbittorrent"
cask "steam"
cask "thunderbird"
cask "vlc"
