tap "mopidy/mopidy"
tap "cjbassi/gotop"
brew "ncspot"
brew "cava"  # visualizer I use w/ ncspot
brew "cmatrix"
brew "cowsay"
brew "figlet"
brew "fortune"
brew "ncmpcpp"
brew "neofetch"
brew "neovim"
brew "pipes-sh"
# brew "prettyping"
brew "socat"  # for ncmpcpp's visualizer
brew "tree"
brew "cjbassi/gotop/gotop"
