tap "d12frosted/emacs-plus"
brew "cscope"
brew "global"
brew "hunspell"
brew "isync"
# brew "ledger"
# brew "mailutils"
brew "msmtp"
brew "notmuch"
brew "pinentry-mac"
brew "emacs-plus"
cask "protonmail-bridge"
