tap "d12frosted/emacs-plus"
brew "automake"  # seems to be necessary for emacs to build zmq for jupyter
brew "cscope"
brew "global"
brew "hunspell"
brew "isync"
# brew "ledger"
# brew "mailutils"
brew "msmtp"
brew "notmuch"
brew "pinentry-mac"
brew "emacs-plus"
cask "protonmail-bridge"
