brew "gerbv"
brew "ykman"
cask "darktable"
cask "discord"
cask "gimp"
cask "hammerspoon"
cask "inkscape"
cask "kap"  # screen recording
cask "kicad"
cask "libreoffice"
cask "malwarebytes"
cask "obs"
cask "qbittorrent"
cask "steam"
cask "vlc"
